language: go

go:
- '1.9'
- '1.10'

install:
# tools
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install
- go get github.com/mattn/goveralls
# dependencies
- go get github.com/pkg/errors
- go get github.com/stretchr/testify/...
- go get github.com/DATA-DOG/go-sqlmock
- go get github.com/lib/pq

services:
- postgresql

before_script:
- psql -U postgres -c "ALTER ROLE postgres WITH PASSWORD 'postgres';"

script:
- gometalinter --config=.gometalinter.json --deadline=10m .
- go test -v -tags=integration -covermode=count -coverprofile=profile.cov .

after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci
